# -*- coding: utf-8 -*-
"""hw python -08 -easy-Homework 4: Conditional Count .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Teec3liLXpYrjK2vCbKeEvIcSGKvVXD1
"""

x= int(input())
a,b,c,d,e=map(int,input().split())
gcounter=0
scounter=0
if(x>=a):
    scounter+=1
else:
   gcounter+=1

if(x>=b):
    scounter+=1
else:
   gcounter+=1
if(x>=c):
    scounter+=1
else:
   gcounter+=1
if(x>=d):
    scounter+=1
else:
   gcounter+=1
if(x>=e):
    scounter+=1
else:
   gcounter+=1
print(scounter,end =" ")
print(gcounter)