# -*- coding: utf-8 -*-
"""hw python -08 -easy-Homework 2: Sort 3 numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Teec3liLXpYrjK2vCbKeEvIcSGKvVXD1
"""

a, b,c = map(int, input().split())
if a<b and a<c:
    print(a,end=" ")
    if b<c:
        print(b,end=" ")
        print(c,end=" ")
    else:
        print(c,end=" ")
        print(b,end=" ")
elif b<a and b<c:
    print(b,end=" ")
    if a<c:
        print(a,end=" ")
        print(c,end=" ")
    else:
        print(c,end=" ")
        print(a,end=" ")
elif c<a and c<b:
    print(c,end=" ")
    if a<b:
        print(a,end=" ")
        print(b,end=" ")
    else:
        print(b,end=" ")
        print(a,end=" ")