# -*- coding: utf-8 -*-
"""hw python -08 -easy-Homework 1: Arithmetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Teec3liLXpYrjK2vCbKeEvIcSGKvVXD1
"""

a, b = map(int, input().split())
if a%2!=0 and b%2!=0:
  print(a*b)
elif a%2==0 and b%2==0:
  print(a/b)
elif a%2!=0 and b%2==0:
  print(a+b)
elif a%2==0 and b%2!=0:
  print(a-b)