# -*- coding: utf-8 -*-
"""hw python -08 -easy-Homework 3: Maximum but constrained .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Teec3liLXpYrjK2vCbKeEvIcSGKvVXD1
"""

a,b,c=map(int, input().split())
if a>b and a>c:
  if a<100:
    print(a)
  elif b>c:
    if b<100:
      print(b)
    else:
      if c<100:
        print(c)
      else :
        print(-1)
if b>a and b>c:
  if b<100:
    print(b)
  elif a>c:
    if a<100:
      print(a)
    else:
      if c<100:
        print(c)
      else :
        print(-1)
if c>b and a<c:
  if c<100:
    print(c)
  elif b>a:
    if b<100:
      print(b)
    else:
      if a<100:
        print(a)
      else :
        print(-1)