# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BehqMYDSEmK0VCboiyIJw5lD28VuCDCm
"""

#Homework 1: Arithmetic



a,b=map(int,input().split)
if a%2==0 and b%2==0:
 print(a*b)
elif a%2!=0 and b%2!=0:
  if b!=0:
    print(a/b)
elif a%2!=0 and b%2==0:
  print(a+b)
else:
  print(a-b)